ERROR:root:
Traceback (most recent call last):
  File "/home/ziaur/PycharmProjects/webscriping/ALJAZEERA NEWS PAPER/scriping.py", line 7, in <module>
    raise Exception
Exception
